### ISSUE TITLE
无法打开链接yaeljiao.github.io， 跳转到http://aerolanding.top/就无法访问了

### ISSUE THREAD

**Issue by lzz20150901** [yaeljiao/yaeljiao.github.io#1]

**Comment by yaeljiao** [comment]
Hi 我打算把刚刚申请的域名绑定到我的博客上,但是域名审批暂时还需要等几天

**Comment by yaeljiao** [comment]
Delete CNANE's content temporary, now [yael.jiao.github.io](https://yaeljiao.github.io/) can be access normally.
